name: Release to Nuget

on: 
  release:
    types: published

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup
      uses: actions/setup-dotnet@v3

    - name: Build
      run: dotnetbuild -c Release

    - name: Test
      run: dotnet test -c Release --no-build

    - name: Package
      run: dotnet pack -c Release --no-build --output .

    - name: Push
      run: dotnet nuget push "*.nupkg" --api-key ${{secrets.nuget_api_key}} --source https://api.nuget.org/v3/index.json 
      
